name: Build docker image
on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get tag
        id: gettag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: piotrpiatyszek+limecraft_build
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: quay.mi2.ai 
      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ 'quay.mi2.ai/piotrpiatyszek/limecraft:' + steps.gettag.outputs.tag }}
          context: '.'
